version: '3.9'

services:
  whitelabel:
    container_name: projeto_whitelabel
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/projeto_whitelabel
      - .:/data/web/static:/projeto_whitelabel/home/static/whitelabel
      - .:/data/web/media:/projeto_whitelabel/home/static/whitelabel/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql_robochat
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env