version: '3.9'

services:
  mglrobochat:
    container_name: projeto_pedilaso
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/projeto_pedilaso
      - .:/data/web/static:/projeto_pedilaso/home/static/pedilaso
      - .:/data/web/media:/projeto_pedilaso/home/static/pedilaso/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql_robochat
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env